apiVersion: v1
kind: ConfigMap
metadata:
  name: scylla-config
data:
  scylla.yaml: |
    cluster_name: sd-testes
    listen_address: $(HOST_IP)
    rpc_address: $(HOST_IP) 
    seed_provider:
      - class_name: org.apache.cassandra.locator.SimpleSeedProvider

    data_file_directories:
      - /var/lib/scylla/data

    commitlog_directory: /var/lib/scylla/commitlog

    endpoint_snitch: SimpleSnitch

    num_tokens: 256
    
    prometheus_address: 0.0.0.0

    keyspace:
      - name: sd-testes
        replica_placement_strategy: org.apache.cassandra.locator.SimpleStrategy
        replication_factor: 2
        tables:
          - name: users
            columns:
              - name: id
                type: uuid
                primary: true
              - name: name
                type: text
              - name: age
                type: int
            persistency:
              - block_size_kb: 64
                sstable_compression: org.apache.cassandra.io.compress.LZ4Compressor
                compression_parameters:
                  chunk_length_kb: 64
        default_consistency_level: TWO
