apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: scylla-db
  labels:
    app: scylla-db
spec:
  selector:
    matchLabels:
      app: scylla-db
  template:
    metadata:
      labels:
        app: scylla-db
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: scylla
      containers:
      - name: scylla-db
        image: scylladb/scylla:5.0.1
        args: ["--seeds", "$SEED_IP"]
        env:
          - name: HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        ports:
        - containerPort: 7000
          name: intra-node

        - containerPort: 7199
          name: jmx
            
        - containerPort: 9042
          name: cql

        - containerPort: 9100
          name: node-exporter

        - containerPort: 9180
          name: prometheus

        - containerPort: 10000
          name: api-server
          
        volumeMounts:
        - name: config-volume
          mountPath: /etc/scylla
      volumes:
      - name: config-volume
        configMap:
          name: scylla-config
          items:
            - key: scylla.yaml
              path: scylla.yaml
