apiVersion: v1
kind: Service
metadata:
  name: scylla-api-server
  labels:
    app: scylla-db
spec:
  selector:
    app: scylla-db
  ports:
    - protocol: TCP
      port: 10000
      targetPort: 10000
