apiVersion: v1
kind: Service
metadata:
  name: scylla-cql
  labels:
    app: scylla-db
spec:
  selector:
    app: scylla-db
  ports:
    - protocol: TCP
      port: 9042
      targetPort: 9042
