apiVersion: v1
kind: Service
metadata:
  name: scylla-db-metrics
  labels:
    app: scylla-db
spec:
  selector:
    app: scylla-db
  ports:
    - protocol: TCP
      port: 9100
      targetPort: 9100
