apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra-stress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra-stress
  template:
    metadata:
      labels:
        app: cassandra-stress
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      containers:
      - name: cassandra-stress
        image: cassandra:latest
        command: ["/bin/bash", "-c"]
        args:
        - |
          sleep 3600
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 1Gi
